// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmYPJ3Bd0_l-H3tMxWZEVL_zQqe37g-hY',
    appId: '1:220879599239:web:21278720a96b0dc6e02a22',
    messagingSenderId: '220879599239',
    projectId: 'whatahoot-9f5e7',
    authDomain: 'whatahoot-9f5e7.firebaseapp.com',
    storageBucket: 'whatahoot-9f5e7.appspot.com',
    measurementId: 'G-PE169Z8P97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjN8N5Tl1R6d4gro5Skn7U1toDEP51ePE',
    appId: '1:220879599239:android:0de4125378eac795e02a22',
    messagingSenderId: '220879599239',
    projectId: 'whatahoot-9f5e7',
    storageBucket: 'whatahoot-9f5e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlnxBDabaoGcSj61EOZzbEpZZqiQOYrGg',
    appId: '1:220879599239:ios:a680647ad5d69b53e02a22',
    messagingSenderId: '220879599239',
    projectId: 'whatahoot-9f5e7',
    storageBucket: 'whatahoot-9f5e7.appspot.com',
    iosBundleId: 'com.example.whatahoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlnxBDabaoGcSj61EOZzbEpZZqiQOYrGg',
    appId: '1:220879599239:ios:3b522ecf58e399f4e02a22',
    messagingSenderId: '220879599239',
    projectId: 'whatahoot-9f5e7',
    storageBucket: 'whatahoot-9f5e7.appspot.com',
    iosBundleId: 'com.example.whatahoot.RunnerTests',
  );
}
